name: playlist_admin
description: playlist-admin - Music library management & Spotube automation
publish_to: 'none'
version: 2.9.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  http_parser: ^4.0.2
  html: ^0.15.4
  win32: ^5.2.0
  fl_chart: ^0.66.0
  ffi: ^2.1.0
  audioplayers: ^6.1.0
  file_picker: ^11.0.3
  flutter_discord_rpc: ^1.1.0
  flutter_rust_bridge: 2.11.1
  crypto: ^3.0.3
  webview_windows:
    path: vendor/webview_windows

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/zhcdict.json
    - assets/tools/
    - assets/tools/rag/
